### ISSUE TITLE
No such file or directory: '/opt/dataset/BIPED/edges/imgs/train/rgbr/aug'

### ISSUE THREAD

**Issue by kiki81524** [xavysp/LDC#23]
I follow the step `python main.py --choose_test_data=-1`, but I encounter the error message below.

I cannot find the file ('/opt/dataset/BIPED/edges/imgs/train/rgbr/aug') in the package.

```(LDC_py38) kiki@RTX4090:~/Kiki_test/LDC$ python main.py --choose_test_data=-1
Number of GPU's available: 1
Pytorch version: 2.0.1+cu117
2024-05-23 15:59:29.228587: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-23 15:59:29.631185: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "main.py", line 525, in <module>
    main(args)
  File "main.py", line 402, in main
    dataset_train = BipedDataset(args.input_dir,
  File "/home/kiki/Kiki_test/LDC/dataset.py", line 465, in __init__
    self.data_index = self._build_index()
  File "/home/kiki/Kiki_test/LDC/dataset.py", line 487, in _build_index
    for directory_name in os.listdir(images_path):
FileNotFoundError: [Errno 2] No such file or directory: '/opt/dataset/BIPED/edges/imgs/train/rgbr/aug'

**Comment by ManthanSh** [comment]
You need to augment the original BIPED dataset. It will create the necessary folders expected. 
You can use https://github.com/xavysp/MBIPED. It is mentioned on the official webpage
